### ISSUE TITLE
Service workers

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-clear-site-data#1]
The name "executionContexts" suggests service workers get rebooted, but it's actually only concerned with browsing contexts. If service worker registrations get removed through "storage", currently running service workers should probably also be halted?

**Comment by wanderview** [comment]
We absolutely have to clear service worker registrations when the origin storage is wiped.  Otherwise service workers will get confused that the stuff they setup in their install event is not there any more.

**Comment by mikewest** [comment]
At some point in the intervening year, we made this explicit in https://w3c.github.io/webappsec-clear-site-data/#clear-dom (step 4).
