### ISSUE TITLE
storage.clear("executionContexts") ends up doing a reload across tabs

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-clear-site-data#21]
This seems like a very strange API that way.

It's also totally underdefined.

**Comment by mikewest** [comment]
It is a very strange API. The goal is to prevent code running in a document from magically reinstantiating an attacker's service worker (or whatever) from data in its existing variables/global/etc.

I'd love something simpler. Do you have an idea how we could improve the approach?

**Comment by annevk** [comment]
I can kinda see the point in the header, but I don't see how an API is going to help with this. If you're compromised, how likely is that you can still invoke this successfully?

Also, should we rename this to "reload browsing contexts"? It seems that's all it does.

**Comment by mikewest** [comment]
> I don't see how an API is going to help with this.

I think I agree with you. I'm going to drop the API from the document for now, as I don't know of any folks who are actually asking for it. The customers I know of at Google aren't interested, and the folks I know of experimenting externally are using the header.

If we end up needing it, it should be straightforward to add back.

> Also, should we rename this to "reload browsing contexts"? It seems that's all it does.

I'm not sure that's any clearer than "execute context". :/

**Comment by annevk** [comment]
It's just that "execute context" is yet another name that's not in use anywhere. Does this also tear down shared workers and service workers? Maybe it should be "reboot environments"? (I can move this to a distinct issue if you want.)

**Comment by mikewest** [comment]
Moved to #23. Closing this out via https://github.com/w3c/webappsec-clear-site-data/commit/1af60c6b342e11106fab55a2a116af76843b7001.
