### ISSUE TITLE
Explainer

### ISSUE THREAD

**Issue by triblondon** [w3c/webappsec-clear-site-data#31]
From the recent [TAG review](https://github.com/w3ctag/design-reviews/issues/62):

Please add an explainer!

**Comment by JakeChampion** [comment]
I believe this was resolved via https://github.com/w3c/webappsec-clear-site-data/commit/18185a02a675a7c10c727378d666d742600c55a6

**Comment by slightlyoff** [comment]
I think we can consider this resolved. Can someone close?
