### ISSUE TITLE
Can you only run this API using HTTPs?

### ISSUE THREAD

**Issue by ayumihamsaki** [w3c/webappsec-clear-site-data#58]
Hello,

We are trying to add this API to our CMS github issue: https://github.com/octobercms/october/pull/4088

My quick question is on testing we are seeing this error message in Google Chrome:

![53345599-fb08bf00-391d-11e9-8587-a9f5cb10ddee](https://user-images.githubusercontent.com/17784082/53533504-0e20b800-3af3-11e9-81ea-a13774243d57.png)

To be honest I am a bit surprised and thought I'd double check to see if we have to have HTTPs only websites using this API. I thought this API would be fine in both HTTP and HTTPs.

Look forward to your reply.

**Comment by mikewest** [comment]
The feature is indeed restricted to HTTPS: see step 1 of https://w3c.github.io/webappsec-clear-site-data/#clear-response. Without this restriction, we can't be sure that the server is actually requesting data clearing, as anything between you and the server could be injecting the header.

Note that some browsers offer the ability to enable features that require secure connections on non-secure sites for testing. For example, Chrome has chrome://flags/#unsafely-treat-insecure-origin-as-secure.

**Comment by ayumihamsaki** [comment]
Thank you for quick reply!
