### ISSUE TITLE
What happens when the server tells the UA to clear site data while sending new data?

### ISSUE THREAD

**Issue by cqueern** [w3c/webappsec-clear-site-data#69]
I don't believe the [spec](https://w3c.github.io/webappsec-clear-site-data/) is clear on what happens in a scenario like the following...

If a new cookie is sent alongside `Clear-Site-Data: "cookies"` in the same response what is the intended behavior from the user agent? Does the UA: 

A) clear site data for cookies and **keep** the new cookie sent alongside 
B) clear site data for cookies and **ignore** new cookie sent alongside 
C) (other)

Thanks for your hard work.

**Comment by annevk** [comment]
This is specified, though somewhat hand-wavy: https://w3c.github.io/webappsec-clear-site-data/#fetch-integration.

**Comment by cqueern** [comment]
Makes sense, thanks @annevk .
